version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: blog_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - blog_db_data:/var/lib/postgresql/data

volumes:
  blog_db_data:
